name: DJANGO Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencias
      working-directory: demo-devops-python
      run: |
        pip install -r requirements.txt
        
    - name: Run Django Tests
      working-directory: demo-devops-python
      run: |
        python manage.py test
        
    - name: Build docker image
      working-directory: demo-devops-python
      run: |
        docker build -t jfmaradiaga/django-devops-app:latest .
        
    - name: Log into Docker hub
      run: |
        echo "$
        {{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
    - name: Push Docker Image to Docker Hub
      run: |
        docker push jfmaradiaga/django-devops-app:latest